export const ANALYTICS_EVENTS = [
  "App.launched",
  "Error.gitFailed",
  "Workspace.created",
  "Workspace.deleted",
  "Workspace.configFileAdded",
  "Workspace.filesCopied",
  "Project.added",
  "Project.removed",
  "User.loggedIn",
  "User.loggedOut",
  "MCP.connected",
  "MCP.sessionFocused",
  "MCP.sessionStatusChanged",
  "Environment.created",
  "Environment.deleted",
  "Environment.attached",
  "Environment.detached",
  "Environment.updated",
  "Editor.launched",
  "Settings.editorChanged",
  "Settings.mcpInstalled",
  "QuickLauncher.toggled",
  "QuickLauncher.navigated",
  "QuickLauncher.workspaceOpened",
  "WorkspaceIsolation.dialogOpened",
  "WorkspaceIsolation.infoDialogOpened",
  "WorkspaceIsolation.introContinued",
  "WorkspaceIsolation.autoEnvEnableAttempted",
  "WorkspaceIsolation.autoEnvEnableCompleted",
  "WorkspaceIsolation.configurationAdvanced",
  "WorkspaceIsolation.activationOffered",
  "WorkspaceIsolation.activationCompleted",
  "WorkspaceIsolation.activationSkipped",
  "WorkspaceIsolation.deactivationCompleted",
  "WorkspaceIsolation.workspaceStateViewed",
  "WorkspaceIsolation.proofDrawerOpened",
  "WorkspaceIsolation.legacyBridgeOpened",
  "WorkspaceIsolation.legacyBridgeSelected",
  "WorkspaceIsolation.saved",
  "WorkspaceIsolation.deleted",
  "Update.completed",
] as const;

export type AnalyticsEvent = (typeof ANALYTICS_EVENTS)[number];

export const isAnalyticsEvent = (value: string): value is AnalyticsEvent =>
  ANALYTICS_EVENTS.includes(value as AnalyticsEvent);
