const scriptLines = [
  "#!/usr/bin/env node",
  'import { promises as fs } from "node:fs";',
  'import os from "node:os";',
  'import path from "node:path";',
  "",
  "const platform = (process.argv[2] ?? 'unknown').toLowerCase();",
  "const galacticHome = process.env.GALACTIC_HOME ?? path.join(os.homedir(), '.galactic');",
  "const stateDirectory = path.join(galacticHome, 'state');",
  "const logPath = path.join(stateDirectory, 'agent-events.ndjson');",
  "",
  "const readStdin = async () => {",
  "  const chunks = [];",
  "  for await (const chunk of process.stdin) chunks.push(Buffer.from(chunk));",
  "  return Buffer.concat(chunks).toString('utf8').trim();",
  "};",
  "",
  "const pick = (input, keys) => {",
  "  for (const key of keys) {",
  "    if (input[key] !== undefined && input[key] !== null && input[key] !== '') return input[key];",
  "  }",
  "  return undefined;",
  "};",
  "",
  "const toTitle = (value) => {",
  "  if (typeof value !== 'string') return undefined;",
  "  const trimmed = value.replace(/\\s+/g, ' ').trim();",
  "  if (!trimmed) return undefined;",
  "  return trimmed.length > 96 ? `${trimmed.slice(0, 93)}...` : trimmed;",
  "};",
  "",
  "const toSessionStarted = (input) => ({",
  "  type: 'session.started',",
  "  sessionId: pick(input, ['session_id', 'sessionId']),",
  "  chatId: pick(input, ['session_id', 'sessionId']),",
  "  title: toTitle(input.prompt) ?? toTitle(input.source) ?? `${platform} session`,",
  "  workspacePath: pick(input, ['cwd']),",
  "  platform,",
  "  startedAt: new Date().toISOString(),",
  "  gitBranch: pick(input, ['git_branch', 'gitBranch']),",
  "});",
  "",
  "const normalize = (input) => {",
  "  const hookEventName = pick(input, ['hook_event_name', 'hookEventName']);",
  "  const sessionId = pick(input, ['session_id', 'sessionId']);",
  "  if (!hookEventName || !sessionId) return [];",
  "  if (hookEventName === 'SessionStart' || hookEventName === 'UserPromptSubmit') return [toSessionStarted(input)];",
  "  if (hookEventName === 'PermissionRequest') {",
  "    return [{ type: 'approval.pending', sessionId, at: new Date().toISOString() }];",
  "  }",
  "  if (hookEventName === 'PostToolUse' || hookEventName === 'PostToolUseFailure') {",
  "    return [{ type: 'approval.cleared', sessionId, at: new Date().toISOString() }];",
  "  }",
  "  if (hookEventName === 'Stop' || hookEventName === 'SessionEnd') {",
  "    const reason = String(input.reason ?? '').toLowerCase();",
  "    const status = reason.includes('cancel') ? 'cancelled' : reason.includes('error') ? 'error' : 'ok';",
  "    return [{ type: 'session.finished', sessionId, endedAt: new Date().toISOString(), status }];",
  "  }",
  "  return [];",
  "};",
  "",
  "const main = async () => {",
  "  const raw = await readStdin();",
  "  if (!raw) return;",
  "  const parsed = JSON.parse(raw);",
  "  const events = normalize(parsed).filter((event) => Boolean(event.sessionId));",
  "  if (events.length === 0) return;",
  "  await fs.mkdir(stateDirectory, { recursive: true });",
  "  const payload = `${events.map((event) => JSON.stringify(event)).join('\\n')}\\n`;",
  "  await fs.appendFile(logPath, payload, 'utf8');",
  "};",
  "",
  "main().catch((error) => {",
  "  const message = error instanceof Error ? error.message : String(error);",
  "  process.stderr.write(`${message}\\n`);",
  "  process.exitCode = 1;",
  "});",
  "",
];

export const getHookRunnerSource = () => `${scriptLines.join("\n")}`;
